/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gr.dsigned.jmvc.models;

import gr.dsigned.jmvc.Bean;
import gr.dsigned.jmvc.framework.Jmvc;
import java.sql.ResultSet;
import java.util.ArrayList;
import junit.framework.*;

/**
 *
 * @author Alkis Kafkis <a.kafkis@phiresoft.com>
 */
public class TestIssues extends TestCase {

    public void testCrudIssue() throws Exception {
        Jmvc framework = Jmvc.getInstance();
        Issue issueModel = framework.loadModel("Issue");

        ArrayList<Bean> initIssues = issueModel.getBySiteId("1");
        ResultSet rs = issueModel.insertIssue("1", "testIssue", "testIssue desc");
        String autoGeneratedKey = null;
        if (rs.next()) {
            autoGeneratedKey = rs.getString(1);
        }
        Bean issue = issueModel.getIssueById(autoGeneratedKey);
        assertEquals(initIssues.size() + 1, issueModel.getBySiteId("1").size());
        
        issueModel.updateIssue(issue.get("id"), "new label", "new desc");
        assertEquals("new label", issueModel.getIssueById(issue.get("id")).get("label"));
        assertEquals("new desc", issueModel.getIssueById(issue.get("id")).get("description"));
        
        issueModel.delete(issue.get("id"));
        assertEquals(initIssues.size(), issueModel.getBySiteId("1").size());
    }
}
